Repository big-neon/bn-api, pull requests merged in 2019-12, with the labels that each got.

#1619 Email: Fixed time stamp for event and abbreviation for states
  api/src/utils/communication/mod.rs
  db/src/services/country_lookup.rs
Labels: Requires QA

#1628 Use new tickets url for globee payments
  api/src/controllers/payments.rs
  api/src/domain_events/executors/broadcast_push_notification.rs
  db/src/models/orders.rs
Labels: Requires QA

#1623 Refund override behavior for manual overrides
  api/src/controllers/orders.rs
  api/tests/functional/base/orders.rs
  api/tests/functional/orders.rs
  db/migrations/20191202220238_refund-override-modifications/down.sql
  db/migrations/20191202220238_refund-override-modifications/up.sql
  db/src/models/activities.rs
  db/src/models/events.rs
  db/src/models/order_items.rs
  db/src/models/orders.rs
  db/src/models/refunds.rs
  db/src/models/scopes.rs
  db/src/models/settlements.rs
  db/src/models/users.rs
  db/src/queries/order_details.sql
  db/src/schema.rs
  db/src/test/builders/refund_builder.rs
  db/tests/unit/activities.rs
  db/tests/unit/codes.rs
  db/tests/unit/events.rs
  db/tests/unit/order_items.rs
  db/tests/unit/orders.rs
  db/tests/unit/organizations.rs
  db/tests/unit/refunded_tickets.rs
  db/tests/unit/refunds.rs
  db/tests/unit/reports.rs
  db/tests/unit/settlements.rs
  db/tests/unit/users.rs
Labels: Can Merge

#1620 Venue search with special chars stripped out
  db/src/models/events.rs
  db/src/utils/regexes.rs
  db/tests/unit/events.rs
Labels: Can Merge

#1627 Lockdown transfers around redeemed tickets
  api/src/controllers/events.rs
  db/src/models/ticket_instances.rs
  db/src/models/transfer_tickets.rs
  db/tests/unit/ticket_instances.rs
  db/tests/unit/transfer_tickets.rs
Labels: Can Merge

#1618 Add CubeJS Secret to Event Dashboard
  .drone.yml
  Cargo.lock
  api/.env.sample
  api/src/config.rs
  api/src/controllers/analytics.rs
  api/src/controllers/events.rs
  api/src/errors/big_neon_error.rs
  api/src/errors/web_error.rs
  api/tests/functional/base/events.rs
  api/tests/functional/events.rs
  db/migrations/20191120121212_data_fix_analytics/down.sql
  db/migrations/20191120121212_data_fix_analytics/up.sql
  db/src/models/analytics/page_views.rs
  db/src/schema.rs
  http/Cargo.toml
Labels: Requires QA

#1643 [High Risk] Add a better concurrency check and error message
  db/src/models/domain_actions.rs
Labels: Requires QA, high priority
