Repository big-neon/bn-api, pull requests merged in 2019-04, with the labels that each got.

#1170 Log response from Facebook login
  api/src/controllers/external/facebook.rs
Labels: in progress

#1171 Updated README with build status
  README.md
Labels: in progress

#1159 Improve order unit tests
  db/src/models/orders.rs
  db/tests/unit/orders.rs
Labels: in progress

#1169 Add more unit tests
  db/tests/unit/assets.rs
  db/tests/unit/events.rs
  db/tests/unit/organization_invites.rs
  db/tests/unit/regions.rs
Labels: in progress

#1172 Using the public rust images to build
  Dockerfile
Labels: in progress

#1168 Change codes API to accept multiple redemption codes in future
  api/src/config.rs
  api/src/controllers/codes.rs
  api/src/models/user_display_ticket_type.rs
  api/tests/functional/base/codes.rs
  api/tests/functional/codes.rs
  db/src/models/codes.rs
  db/tests/unit/codes.rs
  integration-tests/bigneon-tests.postman_collection.json
Labels: in progress

#1174 Docker image was missing ca-certificates
  Dockerfile
Labels: in progress

#1173 Allow CORS clients to access x-app-version
  api/src/server.rs
Labels: in progress

#1143 Search and pagination support for transaction details report:
  api/src/controllers/reports.rs
  api/src/models/payload.rs
  api/tests/functional/base/reports.rs
  api/tests/functional/reports.rs
  db/src/models/reports.rs
  db/src/queries/reports/reports_transaction_details.sql
  db/tests/unit/reports.rs
Labels: in progress, needs web changes

#1179 Make Facebook email optional
  api/src/controllers/external/facebook.rs
  db/src/models/users.rs
  db/tests/unit/users.rs
Labels: Urgent, in progress

#1180 Reedem key not returning at the right time
  db/src/models/ticket_instances.rs
  db/src/queries/retrieve_guest_list.sql
Labels: in progress

#1178 Fix bug found while updating discount codes
  api/src/controllers/redemption_codes.rs
  api/src/models/display_ticket_pricing.rs
  api/tests/functional/redemption_codes.rs
  db/src/models/codes.rs
  integration-tests/bigneon-tests.postman_collection.json
Labels: in progress

#1184 Added promo code details to transaction details report
  api/tests/functional/base/reports.rs
  db/src/models/reports.rs
  db/src/queries/reports/reports_transaction_details.sql
  db/tests/unit/reports.rs
Labels: in progress

#1183 Addressing QA issues
  api/src/controllers/codes.rs
  api/tests/functional/base/codes.rs
  api/tests/functional/codes.rs
  db/src/models/codes.rs
  db/tests/unit/codes.rs
  db/tests/unit/ticket_type_codes.rs
Labels: in progress

#1185 Promo reports SQL
  db/functions/functions.sql
  db/src/models/reports.rs
  db/src/queries/find_all_events_for_organization.sql
  db/src/queries/reports/reports_event_summary_sales.sql
  db/src/queries/reports/reports_transaction_details.sql
Labels: in progress

#1187 Fix bug in a SQL function to check the per_user limit for promo codes
  db/functions/functions.sql
Labels: in progress

#1176 Added a generic pagination override
  api/src/controllers/events.rs
  api/tests/functional/events.rs
  db/src/models/events.rs
  db/src/models/paging.rs
  db/src/utils/errors.rs
  db/src/utils/mod.rs
  db/src/utils/pagination.rs
  db/tests/unit/events.rs
Labels: in progress, needs web changes

#1190 Fix rounding error on IPN
  api/src/domain_events/executors/process_payment_ipn.rs
  db/src/models/orders.rs
Labels: in progress

#1175 Add tiered ticket types
  api/src/controllers/cart.rs
  api/src/controllers/events.rs
  api/src/controllers/ticket_types.rs
  api/src/models/admin_display_ticket_type.rs
  api/src/models/user_display_ticket_type.rs
  api/tests/functional/base/cart.rs
  api/tests/functional/base/events.rs
  api/tests/functional/base/ticket_types.rs
  api/tests/functional/base/tickets.rs
  api/tests/functional/cart.rs
  api/tests/functional/ticket_types.rs
  api/tests/unit/models/user_display_ticket_type.rs
  db/migrations/20190401121212_add_parent_ticket_type_id/down.sql
  db/migrations/20190401121212_add_parent_ticket_type_id/up.sql
  db/src/models/enums.rs
  db/src/models/events.rs
  db/src/models/orders.rs
  db/src/models/ticket_pricing.rs
  db/src/models/ticket_types.rs
  db/src/schema.rs
  db/src/test/builders/event_builder.rs
  db/src/test/times.rs
  db/src/validators/start_date_before_end_date_validator.rs
  db/tests/unit/artists.rs
  db/tests/unit/assets.rs
  db/tests/unit/codes.rs
  db/tests/unit/events.rs
  db/tests/unit/orders.rs
  db/tests/unit/ticket_pricing.rs
  db/tests/unit/ticket_types.rs
  integration-tests/bigneon-tests.postman_collection.json
Labels: in progress

#1192 Fixed the sales_total_in_cents for event index query
  db/src/queries/find_all_events_for_organization.sql
Labels: in progress

#1191 Add status to Codes to allow for deleting of codes and updated uniqueness constraints
  api/src/controllers/codes.rs
  api/src/controllers/comps.rs
  api/tests/functional/base/comps.rs
  db/functions/functions.sql
  db/migrations/20190409064759_add_code_status_update_unique_constraint/down.sql
  db/migrations/20190409064759_add_code_status_update_unique_constraint/up.sql
  db/src/models/codes.rs
  db/src/models/enums.rs
  db/src/models/holds.rs
  db/src/models/ticket_types.rs
  db/src/schema.rs
  db/src/test/builders/code_builder.rs
  db/src/validators/redemption_code_uniqueness_validator.rs
  db/tests/unit/codes.rs
  db/tests/unit/holds.rs
  db/tests/unit/order_items.rs
  db/tests/unit/orders.rs
Labels: in progress

#1196 Added hold /promo id, name and code to event summary report
  db/src/models/reports.rs
  db/src/queries/reports/reports_event_summary_sales.sql
Labels: in progress

#1198 Fix refunds on discounted items
  db/src/models/order_items.rs
  db/src/models/orders.rs
Labels: in progress

#1194 Cart limit modifications
  api/src/models/user_display_ticket_type.rs
  api/tests/unit/models/user_display_ticket_type.rs
  db/functions/functions.sql
  db/migrations/20190409173024_codes_remove_max_tickets_constraint/down.sql
  db/migrations/20190409173024_codes_remove_max_tickets_constraint/up.sql
  db/src/models/order_items.rs
  db/src/models/orders.rs
  db/src/schema.rs
  db/tests/unit/order_items.rs
  db/tests/unit/orders.rs
  integration-tests/bigneon-tests.postman_collection.json
Labels: in progress

#1202 Fix start date on Tiered Pricing
  api/src/models/user_display_ticket_type.rs
  db/src/models/ticket_types.rs
Labels: Urgent, in progress

#1207 Fix bug with promo codes with the same redemption code
  api/src/controllers/redemption_codes.rs
  api/src/models/admin_display_ticket_type.rs
  api/src/models/display_ticket_pricing.rs
  api/src/models/user_display_ticket_type.rs
  api/tests/unit/models/display_ticket_pricing.rs
  api/tests/unit/models/user_display_ticket_type.rs
  db/src/models/holds.rs
  db/src/models/orders.rs
  db/src/schema.rs
  db/tests/unit/codes.rs
  db/tests/unit/comps.rs
Labels: in progress

#1203 Hold listing should not include children
  api/src/controllers/events.rs
  api/tests/functional/base/events.rs
  db/src/models/holds.rs
  db/src/models/ticket_instances.rs
  db/tests/unit/holds.rs
Labels: in progress

#1199 IPN: Try to refresh expired carts during processing
  api/src/controllers/payments.rs
  api/src/domain_events/executors/process_payment_ipn.rs
  db/src/models/orders.rs
  db/src/models/payments.rs
  db/src/models/ticket_instances.rs
  db/tests/unit/orders.rs
  db/tests/unit/ticket_instances.rs
Labels: in progress

#1209 Add changes_since filter to guest lists
  .gitignore
  api/src/controllers/events.rs
  api/tests/functional/events.rs
  db/src/models/events.rs
  db/src/models/redeemable_ticket.rs
  db/src/models/ticket_instances.rs
  db/src/queries/retrieve_guest_list.sql
  db/tests/unit/events.rs
Labels: in progress

#1200 Refactor SoldOutBehavior to Visibility
  api/src/auth/user.rs
  api/src/controllers/events.rs
  api/src/controllers/ticket_types.rs
  api/src/models/admin_display_ticket_type.rs
  api/src/models/event_show_result.rs
  api/src/models/mod.rs
  api/src/models/path_parameters.rs
  api/src/models/user_display_ticket_type.rs
  api/tests/functional/base/events.rs
  api/tests/functional/base/ticket_types.rs
  api/tests/functional/base/tickets.rs
  api/tests/functional/events.rs
  api/tests/functional/ticket_types.rs
  api/tests/functional/tickets.rs
  api/tests/mod.rs
  api/tests/support/mod.rs
  api/tests/support/test_request.rs
  api/tests/unit/models/user_display_ticket_type.rs
  db/migrations/20190411120000_add_ticket_type_visibility/down.sql
  db/migrations/20190411120000_add_ticket_type_visibility/up.sql
  db/src/models/enums.rs
  db/src/models/events.rs
  db/src/models/orders.rs
  db/src/models/organizations.rs
  db/src/models/ticket_types.rs
  db/src/schema.rs
  db/src/test/builders/event_builder.rs
  db/src/test/builders/mod.rs
  db/src/test/builders/ticket_type_builder.rs
  db/src/utils/dates.rs
  db/tests/unit/assets.rs
  db/tests/unit/events.rs
  db/tests/unit/orders.rs
  db/tests/unit/ticket_types.rs
  integration-tests/mocha/test/01 Setup/07 OrgMember - create tickets - Default pricing.js
  integration-tests/mocha/test/01 Setup/08 OrgMember - update tickets - Default pricing.js
  integration-tests/mocha/test/01 Setup/09 OrgMember - create tickets - VIP.js
  integration-tests/mocha/test/01 Setup/10 Admin - create tickets - fail negative pricing.js
  integration-tests/mocha/test/01 Setup/11 OrgMember - create tickets - VIP - Box office Only.js
  integration-tests/mocha/test/01 Setup/12 OrgMember - create tickets - fails due to validation errors.js
  integration-tests/mocha/test/01 Setup/13 OrgMember - create tickets - GA.js
  integration-tests/mocha/test/01 Setup/14 OrgMember - create tickets - GA for cancellation.js
Labels: in progress

#1204 Add report Sales by organization
  db/build.rs
  db/functions/event_fees_per_event.sql
  db/functions/functions.sql
  db/functions/order_items_ticket_type_id_valid_for_access_code.sql
  db/functions/redemption_code_unique_per_event.sql
  db/functions/report_ticket_sales_by_organization.sql
  db/functions/ticket_count_per_ticket_type.sql
  db/functions/ticket_sales_per_ticket_pricing.sql
Labels: in progress

#1211 Add handling of credit card fees to orders and organization admin
  api/src/controllers/organizations.rs
  api/tests/functional/base/organizations.rs
  db/src/models/enums.rs
  db/src/models/order_items.rs
  db/src/models/orders.rs
  db/src/models/organizations.rs
  db/src/test/builders/organization_builder.rs
  db/tests/unit/organizations.rs
Labels: in progress

#1216 Invite fixes
  api/src/communications/mailers/user.rs
  api/src/controllers/organization_invites.rs
  api/src/controllers/user_invites.rs
  api/src/utils/communication/mod.rs
  api/tests/functional/organization_invites.rs
Labels: in progress

#1217 Add timezone to tickets endpoint
  db/src/models/venues.rs
Labels: in progress

#1208 Transfers table
  api/src/controllers/tickets.rs
  api/tests/functional/orders.rs
  db/migrations/20190412180605_transfers/down.sql
  db/migrations/20190412180605_transfers/up.sql
  db/src/models/enums.rs
  db/src/models/mod.rs
  db/src/models/ticket_instances.rs
  db/src/models/transfers.rs
  db/src/queries/add_tickets_to_hold.sql
  db/src/queries/nullify_tickets.sql
  db/src/queries/release_tickets.sql
  db/src/queries/release_tickets_from_hold.sql
  db/src/queries/reserve_tickets.sql
  db/src/schema.rs
  db/tests/unit/mod.rs
  db/tests/unit/ticket_instances.rs
  db/tests/unit/transfers.rs
  db/tests/unit/users.rs
Labels: in progress

#1220 Datafix ticket type Hide -> Hidden
  db/migrations/20190423143146_fix_enum_hide_to_hidden/down.sql
  db/migrations/20190423143146_fix_enum_hide_to_hidden/up.sql
Labels: in progress

#1219 Add campaign tracking data
  api/src/controllers/cart.rs
  api/tests/functional/base/cart.rs
  api/tests/functional/cart.rs
  db/migrations/20190418121122_add_tracking_data_to_order/down.sql
  db/migrations/20190418121122_add_tracking_data_to_order/up.sql
  db/src/models/enums.rs
  db/src/models/orders.rs
  db/src/schema.rs
  integration-tests/mocha/helpers/cart.js
  integration-tests/mocha/helpers/events.js
  integration-tests/mocha/helpers/requests.js
  integration-tests/mocha/test/Referral Tracking/User replace cart - facebook.js
  integration-tests/mocha/test/Referral Tracking/User replace cart - google ads.js
  integration-tests/mocha/test/Referral Tracking/User replace cart - refererrer.js
Labels: in progress

#1085 [DNM] Hold split modifications / improvements
  api/src/controllers/comps.rs
  api/src/controllers/holds.rs
  api/src/routing.rs
  api/tests/functional/base/holds.rs
  api/tests/functional/holds.rs
  db/src/models/holds.rs
  db/src/test/builders/hold_builder.rs
  db/tests/unit/comps.rs
  db/tests/unit/holds.rs
Labels: in progress

#1221 Short link for codes and holds
  api/src/controllers/codes.rs
  api/src/controllers/holds.rs
  api/src/routing.rs
  api/src/utils/deep_linker.rs
  branch_rs/src/lib.rs
  integration-tests/mocha/test/02 Codes/04_1 OrgMember - read code link.js
  integration-tests/mocha/test/03 Holds/07 OrgMember - read hold link.js
Labels: in progress

#1224 Fixed bug that counted cancelled ticket_types for ticket count reports
  db/functions/ticket_count_per_ticket_type.sql
Labels: in progress

#1223 Event promo codes report backend
  api/src/controllers/reports.rs
  db/build.rs
  db/functions/ticket_sales_per_ticket_pricing.sql
  db/src/models/reports.rs
  db/src/schema.rs
  db/src/test/builders/ticket_type_builder.rs
  db/tests/unit/reports.rs
Labels: in progress

#1227 Removed http keep alive
  api/src/server.rs
Labels: in progress

#1225 Fixed visibility check
  api/src/controllers/events.rs
Labels: in progress

#1229 Adjust admin display ticket type status logic
  api/src/models/admin_display_ticket_type.rs
  api/tests/unit/models/admin_display_ticket_type.rs
  api/tests/unit/models/mod.rs
Labels: in progress

#1230 Add sales_start_time to GET /events/{id}
  api/src/controllers/events.rs
  api/src/models/event_show_result.rs
  api/tests/functional/base/events.rs
Labels: in progress

#1231 Added source data to transaction details report
  api/tests/functional/base/reports.rs
  db/src/models/reports.rs
  db/src/queries/reports/reports_transaction_details.sql
  db/tests/unit/reports.rs
Labels: in progress

#1235 Add platform to orders
  Cargo.lock
  db/Cargo.toml
  db/migrations/20190430135200_add_platform_to_orders/down.sql
  db/migrations/20190430135200_add_platform_to_orders/up.sql
  db/src/lib.rs
  db/src/models/orders.rs
  db/src/queries/reports/reports_transaction_details.sql
  db/src/schema.rs
  db/src/utils/errors.rs
Labels: in progress

#1234 Allow box office refunds
  db/src/models/ticket_instances.rs
Labels: in progress
